slogan: "不一样的2017"

theme: bootstrap
inverse: false

menu:
  - title: 首页
    url: index.html
    intro: "All the articles."
    icon: "fa fa-home"
  - title: 文章
    url: categories/文章/
    intro: "All the categories."
    icon: "fa fa-file"
  - title: 招聘
    url: categories/hr/
    intro: "All the hr."
    icon: "fa fa-tags"
  - title: 找工作
    url: categories/job/
    intro: "All the job."
    icon: "fa fa-briefcase"
  - title: 英雄榜
    url: about/
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: Freemind
    url: https://github.com/wzpan/freemind/
    intro: "Freemind's Github repository."
    icon: "fa fa-github"
  - title: "My Github"
    url: http://www.github.com/nanjingjs
    intro: "My Github account."
    icon: "fa fa-github"

widgets:
- search
- category
- tagcloud
- recent_posts  
- links

rss: 
fancybox: true
favicon: favicon.png
duoshuo_shortname: nanjingjs

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: true
jiathis: false

